= MSOOrchestrator-CLI
// Settings
:idprefix:
:idseparator: -
//ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: macro
:toclevels: 1
endif::[]
ifdef::env-github[]
:branch: master
:status:
:outfilesuffix: .adoc
:!toc-title:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:icons:
:uri-cloudify-cli: http://docs.getcloudify.org/4.1.0/cli/overview/
:uri-cloudify-cli-install: http://docs.getcloudify.org/4.1.0/installation/from-packages/
:uri-docker-image: https://hub.docker.com/r/mso4sc/msoorchestrator-cli/
:uri-cfy-multitenancy: http://docs.getcloudify.org/4.1.0/manager/implement-multi-tenancy/

Orchestration CLI of MSO4SC Project, based on Cloudify CLI. Its goal is to provide an interface to interact with a remote MSOOrchestrator instance. For more information, visit {uri-cloudify-cli}.


== Installation

MSOOrchestrator-CLI offers a vagrant file and a docker image to easily start using the command line. Besides it can be installed following {uri-cloudify-cli-install}[the docs].

=== Docker

At {uri-docker-image}[Docker Hub] you can find the latest build image to start using the CLI.

=== Vagrant

A vagrant file is provided at `/vagrant` folder to create a new Virtual Vox machine with the CLI inside.

NOTE: Modify the path `"../../resources/blueprint-examples"` to bind the blueprint examples repository to your virtual machine. Comment the line if you don't want to bind the examples.


== Usage

To connect to a MSOOrchestrator instance, run the following command with your user credentials and remote host or IP of the orchestrator. If you don't have an orchestrator instance yet, follow <<msoorchestrator_installation>> first.

[source,shell]
----
cfy profile use [IP] -u [USER] -p [PASS]
cfy status
----

[msoorchestrator_installation]
== MSOOrchestrator installation

The MSO Orchestrator, based on cloudify, can be easily installed from this CLI.

Requirements:
* Running instance of MSOOrchestrator-CLI vagrant or docker image.
* Centos 7 remote machine with at least 2 CPUs and 4 Gb of RAM (4 CPUs and 12 Gb RAM recommended), reachable by the CLI and with requiretty disabled in sudoers file.

To install the orchestrator, just execute in the CLI:+
`./bootstrap-manager.sh [Centos HOST] [Centos SSH USER] [Orchestrator NEW ADMIN USER] [Orchestrator NEW ADMIN PASSWORD]`
